API-8373 FIX KR ORDER CREATION
Unicity/Chimera pull request #15
Opened 2024-11-07 21:11 UTC by tom-unicity

bypass fallback query when state has non english characters

2024-11-07 21:30 UTC, wallter approved these changes
co-authored & debugged

2024-11-07 21:34 UTC, DerekHansenUnicity approved these changes

2024-11-07 21:34 UTC, DerekHansenUnicity commented on classes/Unicity/Locale/State.php
> +				if (preg_replace('/[^a-z]/i', '', $state_1) !== '') {
NIT: The indentation seems wrong here

Tabs vs spaces?

2024-11-07 21:49 UTC, DerekHansenUnicity requested changes
I'd like the indentation fixed before mergins

2024-11-07 23:42 UTC, tom-unicity commented on classes/Unicity/Locale/State.php
> +				if (preg_replace('/[^a-z]/i', '', $state_1) !== '') {
done.

2024-11-07 23:54 UTC, DerekHansenUnicity approved these changes

2024-11-08 00:07 UTC, DerekHansenUnicity commented
btw the comments are very helpful

2024-11-13 17:54 UTC, merged